///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("1b62e33c-388c-486f-8588-e14a1e0eb4db")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ArtigianOnLineV9000AppFolder _artigianonlinev9000;
        MyTestRepositoryFolders.AffidatarioV9000MozillaFirefoxAppFolder _affidatariov9000mozillafirefox;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("1b62e33c-388c-486f-8588-e14a1e0eb4db")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "1b62e33c-388c-486f-8588-e14a1e0eb4db", ".\\RepositoryImages\\MyTestRepository1b62e33c.rximgres")
        {
            _artigianonlinev9000 = new MyTestRepositoryFolders.ArtigianOnLineV9000AppFolder(this);
            _affidatariov9000mozillafirefox = new MyTestRepositoryFolders.AffidatarioV9000MozillaFirefoxAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1b62e33c-388c-486f-8588-e14a1e0eb4db")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ArtigianOnLineV9000 folder.
        /// </summary>
        [RepositoryFolder("64a4410e-0433-49f3-9d1d-525b70f32743")]
        public virtual MyTestRepositoryFolders.ArtigianOnLineV9000AppFolder ArtigianOnLineV9000
        {
            get { return _artigianonlinev9000; }
        }

        /// <summary>
        /// The AffidatarioV9000MozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("2cb6b4ab-96d4-412d-98fa-f0d5b2a3491c")]
        public virtual MyTestRepositoryFolders.AffidatarioV9000MozillaFirefoxAppFolder AffidatarioV9000MozillaFirefox
        {
            get { return _affidatariov9000mozillafirefox; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ArtigianOnLineV9000AppFolder folder.
        /// </summary>
        [RepositoryFolder("64a4410e-0433-49f3-9d1d-525b70f32743")]
        public partial class ArtigianOnLineV9000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _wrapperloginInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _gefidamodaldialogcancellinkInfo;
            RepoItemInfo _gefidamodalmessagedialogcancellinkInfo;
            RepoItemInfo _ricercapraticaInfo;
            RepoItemInfo _bodybodybodyhypcercaInfo;
            RepoItemInfo _imageInfo;
            RepoItemInfo _modalpopupwaitingpanelInfo;

            /// <summary>
            /// Creates a new ArtigianOnLineV9000  folder.
            /// </summary>
            public ArtigianOnLineV9000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("ArtigianOnLineV9000", "/dom[@domain='collaudo.artigiancassa.it']", parentFolder, 30000, null, false, "64a4410e-0433-49f3-9d1d-525b70f32743", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "6f5a031c-d2ec-45fd-bf40-7b5aa6e3e551");
                _wrapperloginInfo = new RepoItemInfo(this, "WrapperLogin", ".//form[#'FormMaster']/div[7]/div[3]/div[3]/div[1]", 30000, null, "29dff912-a0a1-4984-b44d-1ef820e2321c");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "61169b47-d2f8-4edd-839e-8d35bdf6f427");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//input[#'submitButton']", 30000, null, "3907c4b0-fa77-4794-9891-779e390e38cd");
                _gefidamodaldialogcancellinkInfo = new RepoItemInfo(this, "GefidaModalDialogCancelLink", ".//a[#'GefidaModalDialog_cancelLink']", 30000, null, "d93eb1b0-da8b-4435-a51f-66c8ee6fe9a9");
                _gefidamodalmessagedialogcancellinkInfo = new RepoItemInfo(this, "GefidaModalMessageDialogCancelLink", ".//a[#'GefidaModalMessageDialog_cancelLink']", 30000, null, "fae69544-6695-4292-8873-60f2e247b2ef");
                _ricercapraticaInfo = new RepoItemInfo(this, "RicercaPratica", ".//li[#'Operazioni_ricercaContainer']/?/?/span[@innertext='ricerca pratica']", 30000, null, "0218d74e-d579-4869-8d3b-daa40c7504a2");
                _bodybodybodyhypcercaInfo = new RepoItemInfo(this, "BodyBodyBodyHypCerca", ".//a[#'Body_Body_Body_hypCerca']", 30000, null, "564aa59f-41e6-4513-9998-a4cb18f8647e");
                _imageInfo = new RepoItemInfo(this, "Image", ".//div[#'Body_Body_Body_pnlRisultato']//table/tbody/tr[7]/td[1]/input[@type='image']", 30000, null, "aaf1a226-0d73-4b1a-a408-18269e0308fa");
                _modalpopupwaitingpanelInfo = new RepoItemInfo(this, "ModalPopupWaitingPanel", ".//div[#'ModalPopupWaitingPanel']", 30000, null, "ebbf2335-0086-4857-a311-50e74a6e305b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("64a4410e-0433-49f3-9d1d-525b70f32743")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("64a4410e-0433-49f3-9d1d-525b70f32743")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("6f5a031c-d2ec-45fd-bf40-7b5aa6e3e551")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("6f5a031c-d2ec-45fd-bf40-7b5aa6e3e551")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The WrapperLogin item.
            /// </summary>
            [RepositoryItem("29dff912-a0a1-4984-b44d-1ef820e2321c")]
            public virtual Ranorex.DivTag WrapperLogin
            {
                get
                {
                    return _wrapperloginInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The WrapperLogin item info.
            /// </summary>
            [RepositoryItemInfo("29dff912-a0a1-4984-b44d-1ef820e2321c")]
            public virtual RepoItemInfo WrapperLoginInfo
            {
                get
                {
                    return _wrapperloginInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("61169b47-d2f8-4edd-839e-8d35bdf6f427")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("61169b47-d2f8-4edd-839e-8d35bdf6f427")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("3907c4b0-fa77-4794-9891-779e390e38cd")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("3907c4b0-fa77-4794-9891-779e390e38cd")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The GefidaModalDialogCancelLink item.
            /// </summary>
            [RepositoryItem("d93eb1b0-da8b-4435-a51f-66c8ee6fe9a9")]
            public virtual Ranorex.ATag GefidaModalDialogCancelLink
            {
                get
                {
                    return _gefidamodaldialogcancellinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GefidaModalDialogCancelLink item info.
            /// </summary>
            [RepositoryItemInfo("d93eb1b0-da8b-4435-a51f-66c8ee6fe9a9")]
            public virtual RepoItemInfo GefidaModalDialogCancelLinkInfo
            {
                get
                {
                    return _gefidamodaldialogcancellinkInfo;
                }
            }

            /// <summary>
            /// The GefidaModalMessageDialogCancelLink item.
            /// </summary>
            [RepositoryItem("fae69544-6695-4292-8873-60f2e247b2ef")]
            public virtual Ranorex.ATag GefidaModalMessageDialogCancelLink
            {
                get
                {
                    return _gefidamodalmessagedialogcancellinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GefidaModalMessageDialogCancelLink item info.
            /// </summary>
            [RepositoryItemInfo("fae69544-6695-4292-8873-60f2e247b2ef")]
            public virtual RepoItemInfo GefidaModalMessageDialogCancelLinkInfo
            {
                get
                {
                    return _gefidamodalmessagedialogcancellinkInfo;
                }
            }

            /// <summary>
            /// The RicercaPratica item.
            /// </summary>
            [RepositoryItem("0218d74e-d579-4869-8d3b-daa40c7504a2")]
            public virtual Ranorex.SpanTag RicercaPratica
            {
                get
                {
                    return _ricercapraticaInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RicercaPratica item info.
            /// </summary>
            [RepositoryItemInfo("0218d74e-d579-4869-8d3b-daa40c7504a2")]
            public virtual RepoItemInfo RicercaPraticaInfo
            {
                get
                {
                    return _ricercapraticaInfo;
                }
            }

            /// <summary>
            /// The BodyBodyBodyHypCerca item.
            /// </summary>
            [RepositoryItem("564aa59f-41e6-4513-9998-a4cb18f8647e")]
            public virtual Ranorex.ATag BodyBodyBodyHypCerca
            {
                get
                {
                    return _bodybodybodyhypcercaInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BodyBodyBodyHypCerca item info.
            /// </summary>
            [RepositoryItemInfo("564aa59f-41e6-4513-9998-a4cb18f8647e")]
            public virtual RepoItemInfo BodyBodyBodyHypCercaInfo
            {
                get
                {
                    return _bodybodybodyhypcercaInfo;
                }
            }

            /// <summary>
            /// The Image item.
            /// </summary>
            [RepositoryItem("aaf1a226-0d73-4b1a-a408-18269e0308fa")]
            public virtual Ranorex.InputTag Image
            {
                get
                {
                    return _imageInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Image item info.
            /// </summary>
            [RepositoryItemInfo("aaf1a226-0d73-4b1a-a408-18269e0308fa")]
            public virtual RepoItemInfo ImageInfo
            {
                get
                {
                    return _imageInfo;
                }
            }

            /// <summary>
            /// The ModalPopupWaitingPanel item.
            /// </summary>
            [RepositoryItem("ebbf2335-0086-4857-a311-50e74a6e305b")]
            public virtual Ranorex.DivTag ModalPopupWaitingPanel
            {
                get
                {
                    return _modalpopupwaitingpanelInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ModalPopupWaitingPanel item info.
            /// </summary>
            [RepositoryItemInfo("ebbf2335-0086-4857-a311-50e74a6e305b")]
            public virtual RepoItemInfo ModalPopupWaitingPanelInfo
            {
                get
                {
                    return _modalpopupwaitingpanelInfo;
                }
            }
        }

        /// <summary>
        /// The AffidatarioV9000MozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("2cb6b4ab-96d4-412d-98fa-f0d5b2a3491c")]
        public partial class AffidatarioV9000MozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _pushbuttonInfo;

            /// <summary>
            /// Creates a new AffidatarioV9000MozillaFirefox  folder.
            /// </summary>
            public AffidatarioV9000MozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AffidatarioV9000MozillaFirefox", "/form[@title>'Affidatario v.9.0.0.0 - Mozilla']", parentFolder, 30000, null, true, "2cb6b4ab-96d4-412d-98fa-f0d5b2a3491c", "")
            {
                _pushbuttonInfo = new RepoItemInfo(this, "PushButton", "toolbar[@accessiblename='Browser tabs']/button[3]", 30000, null, "288d010c-f312-4dba-acf5-c1db973f3f6c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2cb6b4ab-96d4-412d-98fa-f0d5b2a3491c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2cb6b4ab-96d4-412d-98fa-f0d5b2a3491c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PushButton item.
            /// </summary>
            [RepositoryItem("288d010c-f312-4dba-acf5-c1db973f3f6c")]
            public virtual Ranorex.Button PushButton
            {
                get
                {
                    return _pushbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PushButton item info.
            /// </summary>
            [RepositoryItemInfo("288d010c-f312-4dba-acf5-c1db973f3f6c")]
            public virtual RepoItemInfo PushButtonInfo
            {
                get
                {
                    return _pushbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
