///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("88fbff7b-5284-478a-8adf-f829dcd877ff", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'FORMICHIERE' with focus on 'ArtigianOnLineV9000.Username'.", repo.ArtigianOnLineV9000.UsernameInfo, new RecordItemIndex(0));
            repo.ArtigianOnLineV9000.Username.PressKeys("FORMICHIERE");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'password.A1' with focus on 'ArtigianOnLineV9000.Password'.", repo.ArtigianOnLineV9000.PasswordInfo, new RecordItemIndex(1));
            repo.ArtigianOnLineV9000.Password.PressKeys("password.A1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArtigianOnLineV9000.SubmitButton' at 26;10.", repo.ArtigianOnLineV9000.SubmitButtonInfo, new RecordItemIndex(2));
            repo.ArtigianOnLineV9000.SubmitButton.Click("26;10");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArtigianOnLineV9000.GefidaModalDialogCancelLink' at 84;4.", repo.ArtigianOnLineV9000.GefidaModalDialogCancelLinkInfo, new RecordItemIndex(3));
            repo.ArtigianOnLineV9000.GefidaModalDialogCancelLink.Click("84;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArtigianOnLineV9000.RicercaPratica' at 69;5.", repo.ArtigianOnLineV9000.RicercaPraticaInfo, new RecordItemIndex(4));
            repo.ArtigianOnLineV9000.RicercaPratica.Click("69;5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArtigianOnLineV9000.BodyBodyBodyHypCerca' at 25;0.", repo.ArtigianOnLineV9000.BodyBodyBodyHypCercaInfo, new RecordItemIndex(5));
            repo.ArtigianOnLineV9000.BodyBodyBodyHypCerca.Click("25;0");
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Visible' to equal the specified value 'false'. Associated repository item: 'ArtigianOnLineV9000.ModalPopupWaitingPanel'", repo.ArtigianOnLineV9000.ModalPopupWaitingPanelInfo, new RecordItemIndex(6));
            repo.ArtigianOnLineV9000.ModalPopupWaitingPanelInfo.WaitForAttributeEqual(30000, "Visible", "false");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ArtigianOnLineV9000.Image' at 22;11.", repo.ArtigianOnLineV9000.ImageInfo, new RecordItemIndex(7));
            repo.ArtigianOnLineV9000.Image.Click("22;11");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
