///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace WeaAppRanorexTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the WeaAppRanorexTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f9026d2e-b0c4-4038-ad22-e1a081b97669")]
    public partial class WeaAppRanorexTestRepository : RepoGenBaseFolder
    {
        static WeaAppRanorexTestRepository instance = new WeaAppRanorexTestRepository();
        WeaAppRanorexTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the WeaAppRanorexTestRepository element repository.
        /// </summary>
        [RepositoryFolder("f9026d2e-b0c4-4038-ad22-e1a081b97669")]
        public static WeaAppRanorexTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public WeaAppRanorexTestRepository() 
            : base("WeaAppRanorexTestRepository", "/", null, 0, false, "f9026d2e-b0c4-4038-ad22-e1a081b97669", ".\\RepositoryImages\\WeaAppRanorexTestRepositoryf9026d2e.rximgres")
        {
            _applicationundertest = new WeaAppRanorexTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f9026d2e-b0c4-4038-ad22-e1a081b97669")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a6b19ff5-bf98-4e17-9292-9b2a8b8e8b2c")]
        public virtual WeaAppRanorexTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class WeaAppRanorexTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a6b19ff5-bf98-4e17-9292-9b2a8b8e8b2c")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _contactInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _benvenutotestInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='localhost']", parentFolder, 30000, null, false, "a6b19ff5-bf98-4e17-9292-9b2a8b8e8b2c", "")
            {
                _contactInfo = new RepoItemInfo(this, "Contact", "body/div[1]//ul/li[3]/a[@innertext='Contact']", 30000, null, "51fc7fde-a496-4819-a50f-7fad5c4cc623");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "1e68559a-e42f-4096-8d51-43852237c5f7");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "c7142e98-5384-438d-b4ea-ffa7d361c269");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//form[@action='http://localhost/WebApp/Home/SignUp']/input[@type='submit']", 30000, null, "ac0c3953-14e4-4294-831f-a4f7c95c3914");
                _benvenutotestInfo = new RepoItemInfo(this, "BenvenutoTest", "body/div[2]/h3[@innertext='Benvenuto test!!!']", 30000, null, "e7052bab-9975-4317-9ddc-59e842c5deed");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a6b19ff5-bf98-4e17-9292-9b2a8b8e8b2c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a6b19ff5-bf98-4e17-9292-9b2a8b8e8b2c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Contact item.
            /// </summary>
            [RepositoryItem("51fc7fde-a496-4819-a50f-7fad5c4cc623")]
            public virtual Ranorex.ATag Contact
            {
                get
                {
                    return _contactInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Contact item info.
            /// </summary>
            [RepositoryItemInfo("51fc7fde-a496-4819-a50f-7fad5c4cc623")]
            public virtual RepoItemInfo ContactInfo
            {
                get
                {
                    return _contactInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("1e68559a-e42f-4096-8d51-43852237c5f7")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("1e68559a-e42f-4096-8d51-43852237c5f7")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("c7142e98-5384-438d-b4ea-ffa7d361c269")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("c7142e98-5384-438d-b4ea-ffa7d361c269")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("ac0c3953-14e4-4294-831f-a4f7c95c3914")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("ac0c3953-14e4-4294-831f-a4f7c95c3914")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The BenvenutoTest item.
            /// </summary>
            [RepositoryItem("e7052bab-9975-4317-9ddc-59e842c5deed")]
            public virtual Ranorex.H3Tag BenvenutoTest
            {
                get
                {
                    return _benvenutotestInfo.CreateAdapter<Ranorex.H3Tag>(true);
                }
            }

            /// <summary>
            /// The BenvenutoTest item info.
            /// </summary>
            [RepositoryItemInfo("e7052bab-9975-4317-9ddc-59e842c5deed")]
            public virtual RepoItemInfo BenvenutoTestInfo
            {
                get
                {
                    return _benvenutotestInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
